default_platform(:android)

platform :android do
  desc "Build the APK with signing"
  lane :build_apk do
    gradle(
      task: "assembleRelease",
      properties: {
        "android.injected.signing.store.file" => "./keystore_for_testing",
        "android.injected.signing.store.password" => "123456aA@",
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => "123456aA@"
      }
    )
  end
end
