default_platform(:android)

platform :android do
  desc "Build the APK with signing"
  lane :deploy_for_testing do
    puts "Keystore Password: #{ENV["KEYSTORE_PASSWORD"]}"
    puts "Key Password: #{ENV['KEY_PASSWORD']}"
    gradle(
      task: "assembleRelease",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
    firebase_app_distribution(
          app: "1:489199092712:android:e883b6d30cc31b8fd75a5d",
          firebase_cli_token: ENV["FIREBASE_TOKEN"],
          release_notes: "New version available!",
          apk_path: "app/build/outputs/apk/release/app-release.apk"
        )
  end
end
