name: Build APK

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Ruby and Bundler
        run: |
          sudo apt-get install ruby-full
          gem install bundler

      - name: Install Fastlane
        run: |
          gem install fastlane -NV
          bundle install

      - name: Build APK
        run: |
          cd android
          bundle exec fastlane build_apk
